export type Bank = { name: string; domain: string };

// Major US banks offering online banking services. Logo loaded via Clearbit/Logo.dev style URL using domain.
export const US_BANKS: Bank[] = [
  { name: "JPMorgan Chase", domain: "chase.com" },
  { name: "Bank of America", domain: "bankofamerica.com" },
  { name: "Wells Fargo", domain: "wellsfargo.com" },
  { name: "Citibank", domain: "citi.com" },
  { name: "U.S. Bank", domain: "usbank.com" },
  { name: "PNC Bank", domain: "pnc.com" },
  { name: "Truist Bank", domain: "truist.com" },
  { name: "Goldman Sachs Bank (Marcus)", domain: "marcus.com" },
  { name: "Capital One", domain: "capitalone.com" },
  { name: "TD Bank", domain: "td.com" },
  { name: "Bank of New York Mellon", domain: "bnymellon.com" },
  { name: "State Street", domain: "statestreet.com" },
  { name: "HSBC Bank USA", domain: "us.hsbc.com" },
  { name: "Charles Schwab Bank", domain: "schwab.com" },
  { name: "Fifth Third Bank", domain: "53.com" },
  { name: "Citizens Bank", domain: "citizensbank.com" },
  { name: "KeyBank", domain: "key.com" },
  { name: "Ally Bank", domain: "ally.com" },
  { name: "BMO Harris Bank", domain: "bmoharris.com" },
  { name: "Regions Bank", domain: "regions.com" },
  { name: "M&T Bank", domain: "mtb.com" },
  { name: "Huntington Bank", domain: "huntington.com" },
  { name: "American Express National Bank", domain: "americanexpress.com" },
  { name: "Discover Bank", domain: "discover.com" },
  { name: "Synchrony Bank", domain: "synchronybank.com" },
  { name: "USAA Federal Savings Bank", domain: "usaa.com" },
  { name: "Navy Federal Credit Union", domain: "navyfederal.org" },
  { name: "First Republic Bank", domain: "firstrepublic.com" },
  { name: "Silicon Valley Bank", domain: "svb.com" },
  { name: "Signature Bank", domain: "signatureny.com" },
  { name: "Comerica Bank", domain: "comerica.com" },
  { name: "Zions Bank", domain: "zionsbank.com" },
  { name: "First Citizens Bank", domain: "firstcitizens.com" },
  { name: "Santander Bank", domain: "santanderbank.com" },
  { name: "Northern Trust", domain: "northerntrust.com" },
  { name: "City National Bank", domain: "cnb.com" },
  { name: "BBVA USA", domain: "bbvausa.com" },
  { name: "Sallie Mae Bank", domain: "salliemae.com" },
  { name: "Frost Bank", domain: "frostbank.com" },
  { name: "Pacific Western Bank", domain: "pacwest.com" },
  { name: "Western Alliance Bank", domain: "westernalliancebancorporation.com" },
  { name: "East West Bank", domain: "eastwestbank.com" },
  { name: "People's United Bank", domain: "peoples.com" },
  { name: "Webster Bank", domain: "websterbank.com" },
  { name: "Valley National Bank", domain: "valley.com" },
  { name: "Synovus Bank", domain: "synovus.com" },
  { name: "Associated Bank", domain: "associatedbank.com" },
  { name: "Old National Bank", domain: "oldnational.com" },
  { name: "Cadence Bank", domain: "cadencebank.com" },
  { name: "First Horizon Bank", domain: "firsthorizon.com" },
  { name: "Prosperity Bank", domain: "prosperitybankusa.com" },
  { name: "BancorpSouth Bank", domain: "bancorpsouth.com" },
  { name: "UMB Bank", domain: "umb.com" },
  { name: "Arvest Bank", domain: "arvest.com" },
  { name: "Hancock Whitney Bank", domain: "hancockwhitney.com" },
  { name: "Texas Capital Bank", domain: "texascapitalbank.com" },
  { name: "Bank of the West", domain: "bankofthewest.com" },
  { name: "Mechanics Bank", domain: "mechanicsbank.com" },
  { name: "Fulton Bank", domain: "fultonbank.com" },
  { name: "Glacier Bank", domain: "glacierbank.com" },
  { name: "Pinnacle Bank", domain: "pnfp.com" },
  { name: "South State Bank", domain: "southstatebank.com" },
  { name: "Renasant Bank", domain: "renasantbank.com" },
  { name: "Atlantic Union Bank", domain: "atlanticunionbank.com" },
  { name: "Simmons Bank", domain: "simmonsbank.com" },
  { name: "WaFd Bank", domain: "wafdbank.com" },
  { name: "Banner Bank", domain: "bannerbank.com" },
  { name: "Columbia Banking System", domain: "columbiabank.com" },
  { name: "Independent Bank", domain: "independent-bank.com" },
  { name: "Centennial Bank", domain: "my100bank.com" },
  { name: "United Bank", domain: "bankwithunited.com" },
  { name: "Trustmark National Bank", domain: "trustmark.com" },
  { name: "Eastern Bank", domain: "easternbank.com" },
  { name: "Rockland Trust", domain: "rocklandtrust.com" },
  { name: "Berkshire Bank", domain: "berkshirebank.com" },
  { name: "Provident Bank", domain: "provident.bank" },
  { name: "Investors Bank", domain: "investorsbank.com" },
  { name: "Apple Bank", domain: "applebank.com" },
  { name: "Dime Community Bank", domain: "dime.com" },
  { name: "Flagstar Bank", domain: "flagstar.com" },
  { name: "TIAA Bank", domain: "tiaabank.com" },
  { name: "EverBank", domain: "everbank.com" },
  { name: "Bank OZK", domain: "ozk.com" },
  { name: "Pacific Premier Bank", domain: "ppbi.com" },
  { name: "First Interstate Bank", domain: "firstinterstate.com" },
  { name: "Stifel Bank", domain: "stifel.com" },
  { name: "Raymond James Bank", domain: "raymondjames.com" },
  { name: "LendingClub Bank", domain: "lendingclub.com" },
  { name: "Axos Bank", domain: "axosbank.com" },
  { name: "Live Oak Bank", domain: "liveoakbank.com" },
  { name: "Customers Bank", domain: "customersbank.com" },
  { name: "BankUnited", domain: "bankunited.com" },
  { name: "Amerant Bank", domain: "amerantbank.com" },
  { name: "Bremer Bank", domain: "bremer.com" },
  { name: "Varo Bank", domain: "varomoney.com" },
  { name: "Chime", domain: "chime.com" },
  { name: "SoFi Bank", domain: "sofi.com" },
  { name: "Current", domain: "current.com" },
  { name: "Revolut USA", domain: "revolut.com" },
  { name: "Wise USA", domain: "wise.com" },
  { name: "Mercury Bank", domain: "mercury.com" },
  { name: "Bluevine", domain: "bluevine.com" },
  { name: "Brex", domain: "brex.com" },
];

export const bankLogo = (domain: string) =>
  `https://logo.clearbit.com/${domain}`;
